# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terra/market/v1beta1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="terra/market/v1beta1/tx.proto",
    package="terra.market.v1beta1",
    syntax="proto3",
    serialized_options=b"Z*github.com/terra-money/core/x/market/types",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1dterra/market/v1beta1/tx.proto\x12\x14terra.market.v1beta1\x1a\x14gogoproto/gogo.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto"\xa9\x01\n\x07MsgSwap\x12!\n\x06trader\x18\x01 \x01(\tB\x11\xf2\xde\x1f\ryaml:"trader"\x12H\n\noffer_coin\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x19\xf2\xde\x1f\x11yaml:"offer_coin"\xc8\xde\x1f\x00\x12\'\n\task_denom\x18\x03 \x01(\tB\x14\xf2\xde\x1f\x10yaml:"ask_denom":\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00"\x9f\x01\n\x0fMsgSwapResponse\x12\x46\n\tswap_coin\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x18\xf2\xde\x1f\x10yaml:"swap_coin"\xc8\xde\x1f\x00\x12\x44\n\x08swap_fee\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x17\xf2\xde\x1f\x0fyaml:"swap_fee"\xc8\xde\x1f\x00"\xe4\x01\n\x0bMsgSwapSend\x12-\n\x0c\x66rom_address\x18\x01 \x01(\tB\x17\xf2\xde\x1f\x13yaml:"from_address"\x12)\n\nto_address\x18\x02 \x01(\tB\x15\xf2\xde\x1f\x11yaml:"to_address"\x12H\n\noffer_coin\x18\x03 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x19\xf2\xde\x1f\x11yaml:"offer_coin"\xc8\xde\x1f\x00\x12\'\n\task_denom\x18\x04 \x01(\tB\x14\xf2\xde\x1f\x10yaml:"ask_denom":\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00"\xa3\x01\n\x13MsgSwapSendResponse\x12\x46\n\tswap_coin\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x18\xf2\xde\x1f\x10yaml:"swap_coin"\xc8\xde\x1f\x00\x12\x44\n\x08swap_fee\x18\x02 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x17\xf2\xde\x1f\x0fyaml:"swap_fee"\xc8\xde\x1f\x00\x32\xad\x01\n\x03Msg\x12L\n\x04Swap\x12\x1d.terra.market.v1beta1.MsgSwap\x1a%.terra.market.v1beta1.MsgSwapResponse\x12X\n\x08SwapSend\x12!.terra.market.v1beta1.MsgSwapSend\x1a).terra.market.v1beta1.MsgSwapSendResponseB,Z*github.com/terra-money/core/x/market/typesb\x06proto3',
    dependencies=[
        gogoproto_dot_gogo__pb2.DESCRIPTOR,
        cosmos_dot_base_dot_v1beta1_dot_coin__pb2.DESCRIPTOR,
    ],
)


_MSGSWAP = _descriptor.Descriptor(
    name="MsgSwap",
    full_name="terra.market.v1beta1.MsgSwap",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="trader",
            full_name="terra.market.v1beta1.MsgSwap.trader",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\ryaml:"trader"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="offer_coin",
            full_name="terra.market.v1beta1.MsgSwap.offer_coin",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\021yaml:"offer_coin"\310\336\037\000',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="ask_denom",
            full_name="terra.market.v1beta1.MsgSwap.ask_denom",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\020yaml:"ask_denom"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"\350\240\037\000\210\240\037\000",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=110,
    serialized_end=279,
)


_MSGSWAPRESPONSE = _descriptor.Descriptor(
    name="MsgSwapResponse",
    full_name="terra.market.v1beta1.MsgSwapResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="swap_coin",
            full_name="terra.market.v1beta1.MsgSwapResponse.swap_coin",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\020yaml:"swap_coin"\310\336\037\000',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="swap_fee",
            full_name="terra.market.v1beta1.MsgSwapResponse.swap_fee",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\017yaml:"swap_fee"\310\336\037\000',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=282,
    serialized_end=441,
)


_MSGSWAPSEND = _descriptor.Descriptor(
    name="MsgSwapSend",
    full_name="terra.market.v1beta1.MsgSwapSend",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="from_address",
            full_name="terra.market.v1beta1.MsgSwapSend.from_address",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\023yaml:"from_address"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="to_address",
            full_name="terra.market.v1beta1.MsgSwapSend.to_address",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\021yaml:"to_address"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="offer_coin",
            full_name="terra.market.v1beta1.MsgSwapSend.offer_coin",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\021yaml:"offer_coin"\310\336\037\000',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="ask_denom",
            full_name="terra.market.v1beta1.MsgSwapSend.ask_denom",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\020yaml:"ask_denom"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"\350\240\037\000\210\240\037\000",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=444,
    serialized_end=672,
)


_MSGSWAPSENDRESPONSE = _descriptor.Descriptor(
    name="MsgSwapSendResponse",
    full_name="terra.market.v1beta1.MsgSwapSendResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="swap_coin",
            full_name="terra.market.v1beta1.MsgSwapSendResponse.swap_coin",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\020yaml:"swap_coin"\310\336\037\000',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="swap_fee",
            full_name="terra.market.v1beta1.MsgSwapSendResponse.swap_fee",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\017yaml:"swap_fee"\310\336\037\000',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=675,
    serialized_end=838,
)

_MSGSWAP.fields_by_name[
    "offer_coin"
].message_type = cosmos_dot_base_dot_v1beta1_dot_coin__pb2._COIN
_MSGSWAPRESPONSE.fields_by_name[
    "swap_coin"
].message_type = cosmos_dot_base_dot_v1beta1_dot_coin__pb2._COIN
_MSGSWAPRESPONSE.fields_by_name[
    "swap_fee"
].message_type = cosmos_dot_base_dot_v1beta1_dot_coin__pb2._COIN
_MSGSWAPSEND.fields_by_name[
    "offer_coin"
].message_type = cosmos_dot_base_dot_v1beta1_dot_coin__pb2._COIN
_MSGSWAPSENDRESPONSE.fields_by_name[
    "swap_coin"
].message_type = cosmos_dot_base_dot_v1beta1_dot_coin__pb2._COIN
_MSGSWAPSENDRESPONSE.fields_by_name[
    "swap_fee"
].message_type = cosmos_dot_base_dot_v1beta1_dot_coin__pb2._COIN
DESCRIPTOR.message_types_by_name["MsgSwap"] = _MSGSWAP
DESCRIPTOR.message_types_by_name["MsgSwapResponse"] = _MSGSWAPRESPONSE
DESCRIPTOR.message_types_by_name["MsgSwapSend"] = _MSGSWAPSEND
DESCRIPTOR.message_types_by_name["MsgSwapSendResponse"] = _MSGSWAPSENDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgSwap = _reflection.GeneratedProtocolMessageType(
    "MsgSwap",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGSWAP,
        "__module__": "terra.market.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.market.v1beta1.MsgSwap)
    },
)
_sym_db.RegisterMessage(MsgSwap)

MsgSwapResponse = _reflection.GeneratedProtocolMessageType(
    "MsgSwapResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGSWAPRESPONSE,
        "__module__": "terra.market.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.market.v1beta1.MsgSwapResponse)
    },
)
_sym_db.RegisterMessage(MsgSwapResponse)

MsgSwapSend = _reflection.GeneratedProtocolMessageType(
    "MsgSwapSend",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGSWAPSEND,
        "__module__": "terra.market.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.market.v1beta1.MsgSwapSend)
    },
)
_sym_db.RegisterMessage(MsgSwapSend)

MsgSwapSendResponse = _reflection.GeneratedProtocolMessageType(
    "MsgSwapSendResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGSWAPSENDRESPONSE,
        "__module__": "terra.market.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.market.v1beta1.MsgSwapSendResponse)
    },
)
_sym_db.RegisterMessage(MsgSwapSendResponse)


DESCRIPTOR._options = None
_MSGSWAP.fields_by_name["trader"]._options = None
_MSGSWAP.fields_by_name["offer_coin"]._options = None
_MSGSWAP.fields_by_name["ask_denom"]._options = None
_MSGSWAP._options = None
_MSGSWAPRESPONSE.fields_by_name["swap_coin"]._options = None
_MSGSWAPRESPONSE.fields_by_name["swap_fee"]._options = None
_MSGSWAPSEND.fields_by_name["from_address"]._options = None
_MSGSWAPSEND.fields_by_name["to_address"]._options = None
_MSGSWAPSEND.fields_by_name["offer_coin"]._options = None
_MSGSWAPSEND.fields_by_name["ask_denom"]._options = None
_MSGSWAPSEND._options = None
_MSGSWAPSENDRESPONSE.fields_by_name["swap_coin"]._options = None
_MSGSWAPSENDRESPONSE.fields_by_name["swap_fee"]._options = None

_MSG = _descriptor.ServiceDescriptor(
    name="Msg",
    full_name="terra.market.v1beta1.Msg",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=841,
    serialized_end=1014,
    methods=[
        _descriptor.MethodDescriptor(
            name="Swap",
            full_name="terra.market.v1beta1.Msg.Swap",
            index=0,
            containing_service=None,
            input_type=_MSGSWAP,
            output_type=_MSGSWAPRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="SwapSend",
            full_name="terra.market.v1beta1.Msg.SwapSend",
            index=1,
            containing_service=None,
            input_type=_MSGSWAPSEND,
            output_type=_MSGSWAPSENDRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name["Msg"] = _MSG

# @@protoc_insertion_point(module_scope)
