# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ibc/core/connection/v1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from ibc.core.connection.v1 import (
    connection_pb2 as ibc_dot_core_dot_connection_dot_v1_dot_connection__pb2,
)

DESCRIPTOR = _descriptor.FileDescriptor(
    name="ibc/core/connection/v1/genesis.proto",
    package="ibc.core.connection.v1",
    syntax="proto3",
    serialized_options=b"Z9github.com/cosmos/ibc-go/modules/core/03-connection/types",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n$ibc/core/connection/v1/genesis.proto\x12\x16ibc.core.connection.v1\x1a\x14gogoproto/gogo.proto\x1a\'ibc/core/connection/v1/connection.proto"\xc6\x02\n\x0cGenesisState\x12G\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32,.ibc.core.connection.v1.IdentifiedConnectionB\x04\xc8\xde\x1f\x00\x12p\n\x17\x63lient_connection_paths\x18\x02 \x03(\x0b\x32\'.ibc.core.connection.v1.ConnectionPathsB&\xc8\xde\x1f\x00\xf2\xde\x1f\x1eyaml:"client_connection_paths"\x12\x45\n\x18next_connection_sequence\x18\x03 \x01(\x04\x42#\xf2\xde\x1f\x1fyaml:"next_connection_sequence"\x12\x34\n\x06params\x18\x04 \x01(\x0b\x32\x1e.ibc.core.connection.v1.ParamsB\x04\xc8\xde\x1f\x00\x42;Z9github.com/cosmos/ibc-go/modules/core/03-connection/typesb\x06proto3',
    dependencies=[
        gogoproto_dot_gogo__pb2.DESCRIPTOR,
        ibc_dot_core_dot_connection_dot_v1_dot_connection__pb2.DESCRIPTOR,
    ],
)


_GENESISSTATE = _descriptor.Descriptor(
    name="GenesisState",
    full_name="ibc.core.connection.v1.GenesisState",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="connections",
            full_name="ibc.core.connection.v1.GenesisState.connections",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="client_connection_paths",
            full_name="ibc.core.connection.v1.GenesisState.client_connection_paths",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\310\336\037\000\362\336\037\036yaml:"client_connection_paths"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="next_connection_sequence",
            full_name="ibc.core.connection.v1.GenesisState.next_connection_sequence",
            index=2,
            number=3,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\037yaml:"next_connection_sequence"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="params",
            full_name="ibc.core.connection.v1.GenesisState.params",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=128,
    serialized_end=454,
)

_GENESISSTATE.fields_by_name[
    "connections"
].message_type = (
    ibc_dot_core_dot_connection_dot_v1_dot_connection__pb2._IDENTIFIEDCONNECTION
)
_GENESISSTATE.fields_by_name[
    "client_connection_paths"
].message_type = ibc_dot_core_dot_connection_dot_v1_dot_connection__pb2._CONNECTIONPATHS
_GENESISSTATE.fields_by_name[
    "params"
].message_type = ibc_dot_core_dot_connection_dot_v1_dot_connection__pb2._PARAMS
DESCRIPTOR.message_types_by_name["GenesisState"] = _GENESISSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType(
    "GenesisState",
    (_message.Message,),
    {
        "DESCRIPTOR": _GENESISSTATE,
        "__module__": "ibc.core.connection.v1.genesis_pb2"
        # @@protoc_insertion_point(class_scope:ibc.core.connection.v1.GenesisState)
    },
)
_sym_db.RegisterMessage(GenesisState)


DESCRIPTOR._options = None
_GENESISSTATE.fields_by_name["connections"]._options = None
_GENESISSTATE.fields_by_name["client_connection_paths"]._options = None
_GENESISSTATE.fields_by_name["next_connection_sequence"]._options = None
_GENESISSTATE.fields_by_name["params"]._options = None
# @@protoc_insertion_point(module_scope)
