# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terra/oracle/v1beta1/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from terra.oracle.v1beta1 import (
    oracle_pb2 as terra_dot_oracle_dot_v1beta1_dot_oracle__pb2,
)

DESCRIPTOR = _descriptor.FileDescriptor(
    name="terra/oracle/v1beta1/genesis.proto",
    package="terra.oracle.v1beta1",
    syntax="proto3",
    serialized_options=b"Z*github.com/terra-money/core/x/oracle/types",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n"terra/oracle/v1beta1/genesis.proto\x12\x14terra.oracle.v1beta1\x1a\x14gogoproto/gogo.proto\x1a!terra/oracle/v1beta1/oracle.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto"\xa6\x04\n\x0cGenesisState\x12\x32\n\x06params\x18\x01 \x01(\x0b\x32\x1c.terra.oracle.v1beta1.ParamsB\x04\xc8\xde\x1f\x00\x12H\n\x12\x66\x65\x65\x64\x65r_delegations\x18\x02 \x03(\x0b\x32&.terra.oracle.v1beta1.FeederDelegationB\x04\xc8\xde\x1f\x00\x12[\n\x0e\x65xchange_rates\x18\x03 \x03(\x0b\x32\'.terra.oracle.v1beta1.ExchangeRateTupleB\x1a\xaa\xdf\x1f\x12\x45xchangeRateTuples\xc8\xde\x1f\x00\x12>\n\rmiss_counters\x18\x04 \x03(\x0b\x32!.terra.oracle.v1beta1.MissCounterB\x04\xc8\xde\x1f\x00\x12\x62\n aggregate_exchange_rate_prevotes\x18\x05 \x03(\x0b\x32\x32.terra.oracle.v1beta1.AggregateExchangeRatePrevoteB\x04\xc8\xde\x1f\x00\x12\\\n\x1d\x61ggregate_exchange_rate_votes\x18\x06 \x03(\x0b\x32/.terra.oracle.v1beta1.AggregateExchangeRateVoteB\x04\xc8\xde\x1f\x00\x12\x39\n\x0btobin_taxes\x18\x07 \x03(\x0b\x32\x1e.terra.oracle.v1beta1.TobinTaxB\x04\xc8\xde\x1f\x00"E\n\x10\x46\x65\x65\x64\x65rDelegation\x12\x16\n\x0e\x66\x65\x65\x64\x65r_address\x18\x01 \x01(\t\x12\x19\n\x11validator_address\x18\x02 \x01(\t">\n\x0bMissCounter\x12\x19\n\x11validator_address\x18\x01 \x01(\t\x12\x14\n\x0cmiss_counter\x18\x02 \x01(\x04"\\\n\x08TobinTax\x12\r\n\x05\x64\x65nom\x18\x01 \x01(\t\x12\x41\n\ttobin_tax\x18\x02 \x01(\tB.\xda\xde\x1f&github.com/cosmos/cosmos-sdk/types.Dec\xc8\xde\x1f\x00\x42,Z*github.com/terra-money/core/x/oracle/typesb\x06proto3',
    dependencies=[
        gogoproto_dot_gogo__pb2.DESCRIPTOR,
        terra_dot_oracle_dot_v1beta1_dot_oracle__pb2.DESCRIPTOR,
        cosmos_dot_base_dot_v1beta1_dot_coin__pb2.DESCRIPTOR,
    ],
)


_GENESISSTATE = _descriptor.Descriptor(
    name="GenesisState",
    full_name="terra.oracle.v1beta1.GenesisState",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="params",
            full_name="terra.oracle.v1beta1.GenesisState.params",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="feeder_delegations",
            full_name="terra.oracle.v1beta1.GenesisState.feeder_delegations",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="exchange_rates",
            full_name="terra.oracle.v1beta1.GenesisState.exchange_rates",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\252\337\037\022ExchangeRateTuples\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="miss_counters",
            full_name="terra.oracle.v1beta1.GenesisState.miss_counters",
            index=3,
            number=4,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="aggregate_exchange_rate_prevotes",
            full_name="terra.oracle.v1beta1.GenesisState.aggregate_exchange_rate_prevotes",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="aggregate_exchange_rate_votes",
            full_name="terra.oracle.v1beta1.GenesisState.aggregate_exchange_rate_votes",
            index=5,
            number=6,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="tobin_taxes",
            full_name="terra.oracle.v1beta1.GenesisState.tobin_taxes",
            index=6,
            number=7,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=150,
    serialized_end=700,
)


_FEEDERDELEGATION = _descriptor.Descriptor(
    name="FeederDelegation",
    full_name="terra.oracle.v1beta1.FeederDelegation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="feeder_address",
            full_name="terra.oracle.v1beta1.FeederDelegation.feeder_address",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="validator_address",
            full_name="terra.oracle.v1beta1.FeederDelegation.validator_address",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=702,
    serialized_end=771,
)


_MISSCOUNTER = _descriptor.Descriptor(
    name="MissCounter",
    full_name="terra.oracle.v1beta1.MissCounter",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="validator_address",
            full_name="terra.oracle.v1beta1.MissCounter.validator_address",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="miss_counter",
            full_name="terra.oracle.v1beta1.MissCounter.miss_counter",
            index=1,
            number=2,
            type=4,
            cpp_type=4,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=773,
    serialized_end=835,
)


_TOBINTAX = _descriptor.Descriptor(
    name="TobinTax",
    full_name="terra.oracle.v1beta1.TobinTax",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="denom",
            full_name="terra.oracle.v1beta1.TobinTax.denom",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="tobin_tax",
            full_name="terra.oracle.v1beta1.TobinTax.tobin_tax",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\332\336\037&github.com/cosmos/cosmos-sdk/types.Dec\310\336\037\000",
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=837,
    serialized_end=929,
)

_GENESISSTATE.fields_by_name[
    "params"
].message_type = terra_dot_oracle_dot_v1beta1_dot_oracle__pb2._PARAMS
_GENESISSTATE.fields_by_name["feeder_delegations"].message_type = _FEEDERDELEGATION
_GENESISSTATE.fields_by_name[
    "exchange_rates"
].message_type = terra_dot_oracle_dot_v1beta1_dot_oracle__pb2._EXCHANGERATETUPLE
_GENESISSTATE.fields_by_name["miss_counters"].message_type = _MISSCOUNTER
_GENESISSTATE.fields_by_name[
    "aggregate_exchange_rate_prevotes"
].message_type = (
    terra_dot_oracle_dot_v1beta1_dot_oracle__pb2._AGGREGATEEXCHANGERATEPREVOTE
)
_GENESISSTATE.fields_by_name[
    "aggregate_exchange_rate_votes"
].message_type = terra_dot_oracle_dot_v1beta1_dot_oracle__pb2._AGGREGATEEXCHANGERATEVOTE
_GENESISSTATE.fields_by_name["tobin_taxes"].message_type = _TOBINTAX
DESCRIPTOR.message_types_by_name["GenesisState"] = _GENESISSTATE
DESCRIPTOR.message_types_by_name["FeederDelegation"] = _FEEDERDELEGATION
DESCRIPTOR.message_types_by_name["MissCounter"] = _MISSCOUNTER
DESCRIPTOR.message_types_by_name["TobinTax"] = _TOBINTAX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GenesisState = _reflection.GeneratedProtocolMessageType(
    "GenesisState",
    (_message.Message,),
    {
        "DESCRIPTOR": _GENESISSTATE,
        "__module__": "terra.oracle.v1beta1.genesis_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.GenesisState)
    },
)
_sym_db.RegisterMessage(GenesisState)

FeederDelegation = _reflection.GeneratedProtocolMessageType(
    "FeederDelegation",
    (_message.Message,),
    {
        "DESCRIPTOR": _FEEDERDELEGATION,
        "__module__": "terra.oracle.v1beta1.genesis_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.FeederDelegation)
    },
)
_sym_db.RegisterMessage(FeederDelegation)

MissCounter = _reflection.GeneratedProtocolMessageType(
    "MissCounter",
    (_message.Message,),
    {
        "DESCRIPTOR": _MISSCOUNTER,
        "__module__": "terra.oracle.v1beta1.genesis_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.MissCounter)
    },
)
_sym_db.RegisterMessage(MissCounter)

TobinTax = _reflection.GeneratedProtocolMessageType(
    "TobinTax",
    (_message.Message,),
    {
        "DESCRIPTOR": _TOBINTAX,
        "__module__": "terra.oracle.v1beta1.genesis_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.TobinTax)
    },
)
_sym_db.RegisterMessage(TobinTax)


DESCRIPTOR._options = None
_GENESISSTATE.fields_by_name["params"]._options = None
_GENESISSTATE.fields_by_name["feeder_delegations"]._options = None
_GENESISSTATE.fields_by_name["exchange_rates"]._options = None
_GENESISSTATE.fields_by_name["miss_counters"]._options = None
_GENESISSTATE.fields_by_name["aggregate_exchange_rate_prevotes"]._options = None
_GENESISSTATE.fields_by_name["aggregate_exchange_rate_votes"]._options = None
_GENESISSTATE.fields_by_name["tobin_taxes"]._options = None
_TOBINTAX.fields_by_name["tobin_tax"]._options = None
# @@protoc_insertion_point(module_scope)
