# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: terra/oracle/v1beta1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="terra/oracle/v1beta1/tx.proto",
    package="terra.oracle.v1beta1",
    syntax="proto3",
    serialized_options=b"Z*github.com/terra-money/core/x/oracle/types",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x1dterra/oracle/v1beta1/tx.proto\x12\x14terra.oracle.v1beta1\x1a\x14gogoproto/gogo.proto"\x96\x01\n\x1fMsgAggregateExchangeRatePrevote\x12\x1d\n\x04hash\x18\x01 \x01(\tB\x0f\xf2\xde\x1f\x0byaml:"hash"\x12!\n\x06\x66\x65\x65\x64\x65r\x18\x02 \x01(\tB\x11\xf2\xde\x1f\ryaml:"feeder"\x12\'\n\tvalidator\x18\x03 \x01(\tB\x14\xf2\xde\x1f\x10yaml:"validator":\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00")\n\'MsgAggregateExchangeRatePrevoteResponse"\xc6\x01\n\x1cMsgAggregateExchangeRateVote\x12\x1d\n\x04salt\x18\x01 \x01(\tB\x0f\xf2\xde\x1f\x0byaml:"salt"\x12\x31\n\x0e\x65xchange_rates\x18\x02 \x01(\tB\x19\xf2\xde\x1f\x15yaml:"exchange_rates"\x12!\n\x06\x66\x65\x65\x64\x65r\x18\x03 \x01(\tB\x11\xf2\xde\x1f\ryaml:"feeder"\x12\'\n\tvalidator\x18\x04 \x01(\tB\x14\xf2\xde\x1f\x10yaml:"validator":\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00"&\n$MsgAggregateExchangeRateVoteResponse"p\n\x16MsgDelegateFeedConsent\x12%\n\x08operator\x18\x01 \x01(\tB\x13\xf2\xde\x1f\x0fyaml:"operator"\x12%\n\x08\x64\x65legate\x18\x02 \x01(\tB\x13\xf2\xde\x1f\x0fyaml:"delegate":\x08\xe8\xa0\x1f\x00\x88\xa0\x1f\x00" \n\x1eMsgDelegateFeedConsentResponse2\xa5\x03\n\x03Msg\x12\x94\x01\n\x1c\x41ggregateExchangeRatePrevote\x12\x35.terra.oracle.v1beta1.MsgAggregateExchangeRatePrevote\x1a=.terra.oracle.v1beta1.MsgAggregateExchangeRatePrevoteResponse\x12\x8b\x01\n\x19\x41ggregateExchangeRateVote\x12\x32.terra.oracle.v1beta1.MsgAggregateExchangeRateVote\x1a:.terra.oracle.v1beta1.MsgAggregateExchangeRateVoteResponse\x12y\n\x13\x44\x65legateFeedConsent\x12,.terra.oracle.v1beta1.MsgDelegateFeedConsent\x1a\x34.terra.oracle.v1beta1.MsgDelegateFeedConsentResponseB,Z*github.com/terra-money/core/x/oracle/typesb\x06proto3',
    dependencies=[
        gogoproto_dot_gogo__pb2.DESCRIPTOR,
    ],
)


_MSGAGGREGATEEXCHANGERATEPREVOTE = _descriptor.Descriptor(
    name="MsgAggregateExchangeRatePrevote",
    full_name="terra.oracle.v1beta1.MsgAggregateExchangeRatePrevote",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="hash",
            full_name="terra.oracle.v1beta1.MsgAggregateExchangeRatePrevote.hash",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\013yaml:"hash"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="feeder",
            full_name="terra.oracle.v1beta1.MsgAggregateExchangeRatePrevote.feeder",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\ryaml:"feeder"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="validator",
            full_name="terra.oracle.v1beta1.MsgAggregateExchangeRatePrevote.validator",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\020yaml:"validator"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"\350\240\037\000\210\240\037\000",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=78,
    serialized_end=228,
)


_MSGAGGREGATEEXCHANGERATEPREVOTERESPONSE = _descriptor.Descriptor(
    name="MsgAggregateExchangeRatePrevoteResponse",
    full_name="terra.oracle.v1beta1.MsgAggregateExchangeRatePrevoteResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=230,
    serialized_end=271,
)


_MSGAGGREGATEEXCHANGERATEVOTE = _descriptor.Descriptor(
    name="MsgAggregateExchangeRateVote",
    full_name="terra.oracle.v1beta1.MsgAggregateExchangeRateVote",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="salt",
            full_name="terra.oracle.v1beta1.MsgAggregateExchangeRateVote.salt",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\013yaml:"salt"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="exchange_rates",
            full_name="terra.oracle.v1beta1.MsgAggregateExchangeRateVote.exchange_rates",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\025yaml:"exchange_rates"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="feeder",
            full_name="terra.oracle.v1beta1.MsgAggregateExchangeRateVote.feeder",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\ryaml:"feeder"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="validator",
            full_name="terra.oracle.v1beta1.MsgAggregateExchangeRateVote.validator",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\020yaml:"validator"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"\350\240\037\000\210\240\037\000",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=274,
    serialized_end=472,
)


_MSGAGGREGATEEXCHANGERATEVOTERESPONSE = _descriptor.Descriptor(
    name="MsgAggregateExchangeRateVoteResponse",
    full_name="terra.oracle.v1beta1.MsgAggregateExchangeRateVoteResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=474,
    serialized_end=512,
)


_MSGDELEGATEFEEDCONSENT = _descriptor.Descriptor(
    name="MsgDelegateFeedConsent",
    full_name="terra.oracle.v1beta1.MsgDelegateFeedConsent",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="operator",
            full_name="terra.oracle.v1beta1.MsgDelegateFeedConsent.operator",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\017yaml:"operator"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="delegate",
            full_name="terra.oracle.v1beta1.MsgDelegateFeedConsent.delegate",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b'\362\336\037\017yaml:"delegate"',
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=b"\350\240\037\000\210\240\037\000",
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=514,
    serialized_end=626,
)


_MSGDELEGATEFEEDCONSENTRESPONSE = _descriptor.Descriptor(
    name="MsgDelegateFeedConsentResponse",
    full_name="terra.oracle.v1beta1.MsgDelegateFeedConsentResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=628,
    serialized_end=660,
)

DESCRIPTOR.message_types_by_name[
    "MsgAggregateExchangeRatePrevote"
] = _MSGAGGREGATEEXCHANGERATEPREVOTE
DESCRIPTOR.message_types_by_name[
    "MsgAggregateExchangeRatePrevoteResponse"
] = _MSGAGGREGATEEXCHANGERATEPREVOTERESPONSE
DESCRIPTOR.message_types_by_name[
    "MsgAggregateExchangeRateVote"
] = _MSGAGGREGATEEXCHANGERATEVOTE
DESCRIPTOR.message_types_by_name[
    "MsgAggregateExchangeRateVoteResponse"
] = _MSGAGGREGATEEXCHANGERATEVOTERESPONSE
DESCRIPTOR.message_types_by_name["MsgDelegateFeedConsent"] = _MSGDELEGATEFEEDCONSENT
DESCRIPTOR.message_types_by_name[
    "MsgDelegateFeedConsentResponse"
] = _MSGDELEGATEFEEDCONSENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgAggregateExchangeRatePrevote = _reflection.GeneratedProtocolMessageType(
    "MsgAggregateExchangeRatePrevote",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGAGGREGATEEXCHANGERATEPREVOTE,
        "__module__": "terra.oracle.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.MsgAggregateExchangeRatePrevote)
    },
)
_sym_db.RegisterMessage(MsgAggregateExchangeRatePrevote)

MsgAggregateExchangeRatePrevoteResponse = _reflection.GeneratedProtocolMessageType(
    "MsgAggregateExchangeRatePrevoteResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGAGGREGATEEXCHANGERATEPREVOTERESPONSE,
        "__module__": "terra.oracle.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.MsgAggregateExchangeRatePrevoteResponse)
    },
)
_sym_db.RegisterMessage(MsgAggregateExchangeRatePrevoteResponse)

MsgAggregateExchangeRateVote = _reflection.GeneratedProtocolMessageType(
    "MsgAggregateExchangeRateVote",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGAGGREGATEEXCHANGERATEVOTE,
        "__module__": "terra.oracle.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.MsgAggregateExchangeRateVote)
    },
)
_sym_db.RegisterMessage(MsgAggregateExchangeRateVote)

MsgAggregateExchangeRateVoteResponse = _reflection.GeneratedProtocolMessageType(
    "MsgAggregateExchangeRateVoteResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGAGGREGATEEXCHANGERATEVOTERESPONSE,
        "__module__": "terra.oracle.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.MsgAggregateExchangeRateVoteResponse)
    },
)
_sym_db.RegisterMessage(MsgAggregateExchangeRateVoteResponse)

MsgDelegateFeedConsent = _reflection.GeneratedProtocolMessageType(
    "MsgDelegateFeedConsent",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGDELEGATEFEEDCONSENT,
        "__module__": "terra.oracle.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.MsgDelegateFeedConsent)
    },
)
_sym_db.RegisterMessage(MsgDelegateFeedConsent)

MsgDelegateFeedConsentResponse = _reflection.GeneratedProtocolMessageType(
    "MsgDelegateFeedConsentResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGDELEGATEFEEDCONSENTRESPONSE,
        "__module__": "terra.oracle.v1beta1.tx_pb2"
        # @@protoc_insertion_point(class_scope:terra.oracle.v1beta1.MsgDelegateFeedConsentResponse)
    },
)
_sym_db.RegisterMessage(MsgDelegateFeedConsentResponse)


DESCRIPTOR._options = None
_MSGAGGREGATEEXCHANGERATEPREVOTE.fields_by_name["hash"]._options = None
_MSGAGGREGATEEXCHANGERATEPREVOTE.fields_by_name["feeder"]._options = None
_MSGAGGREGATEEXCHANGERATEPREVOTE.fields_by_name["validator"]._options = None
_MSGAGGREGATEEXCHANGERATEPREVOTE._options = None
_MSGAGGREGATEEXCHANGERATEVOTE.fields_by_name["salt"]._options = None
_MSGAGGREGATEEXCHANGERATEVOTE.fields_by_name["exchange_rates"]._options = None
_MSGAGGREGATEEXCHANGERATEVOTE.fields_by_name["feeder"]._options = None
_MSGAGGREGATEEXCHANGERATEVOTE.fields_by_name["validator"]._options = None
_MSGAGGREGATEEXCHANGERATEVOTE._options = None
_MSGDELEGATEFEEDCONSENT.fields_by_name["operator"]._options = None
_MSGDELEGATEFEEDCONSENT.fields_by_name["delegate"]._options = None
_MSGDELEGATEFEEDCONSENT._options = None

_MSG = _descriptor.ServiceDescriptor(
    name="Msg",
    full_name="terra.oracle.v1beta1.Msg",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=663,
    serialized_end=1084,
    methods=[
        _descriptor.MethodDescriptor(
            name="AggregateExchangeRatePrevote",
            full_name="terra.oracle.v1beta1.Msg.AggregateExchangeRatePrevote",
            index=0,
            containing_service=None,
            input_type=_MSGAGGREGATEEXCHANGERATEPREVOTE,
            output_type=_MSGAGGREGATEEXCHANGERATEPREVOTERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="AggregateExchangeRateVote",
            full_name="terra.oracle.v1beta1.Msg.AggregateExchangeRateVote",
            index=1,
            containing_service=None,
            input_type=_MSGAGGREGATEEXCHANGERATEVOTE,
            output_type=_MSGAGGREGATEEXCHANGERATEVOTERESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="DelegateFeedConsent",
            full_name="terra.oracle.v1beta1.Msg.DelegateFeedConsent",
            index=2,
            containing_service=None,
            input_type=_MSGDELEGATEFEEDCONSENT,
            output_type=_MSGDELEGATEFEEDCONSENTRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_MSG)

DESCRIPTOR.services_by_name["Msg"] = _MSG

# @@protoc_insertion_point(module_scope)
